# Generated by Django 5.0.6 on 2024-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, upload_to="logos/"),
        ),
    ]
