# Generated by Django 5.0.6 on 2024-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
