# Generated by Django 5.0.6 on 2024-07-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="notes",
            new_name="cover_letter",
        ),
    ]
