# Generated by Django 5.0.6 on 2024-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_rename_notes_application_cover_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(default="Lorem Ipsum"),
            preserve_default=False,
        ),
    ]
